packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': false
  bufferutil: true
  ccxt: true
  esbuild: false
  prisma: false
  sharp: true
  unrs-resolver: true
