/**
 * Applies the cost model (src/costs.ts) to the same 46 trade outcomes
 * already generated by the lifecycle simulator (scripts/signal-outcomes.ts)
 * — no re-simulation, no strategy/logic changes. Fee/slippage rates come
 * from the real configuration layer (SystemConfiguration), not hardcoded
 * values. Sizing uses the same formula as decideTrade in src/engine.ts
 * (riskAmount / ATR), with the same assumed accountSize=10000 used
 * throughout prior backtest/diagnostics scripts (the real configured
 * Settings.accountSize is 0, which would make every trade's risk amount
 * zero and the cost model trivially inert).
 */
import { getSettings, getSystemConfiguration } from "@sol-edge/db";
import { type CostRates } from "@sol-edge/analytics";
import { loadHistoricalSignals } from "./historicalSignals";
import { simulateTrade, type TradeResult } from "@sol-edge/analytics";

const ASSUMED_ACCOUNT_SIZE = 10000; // see header note — real configured value is 0

function aggregate(results: TradeResult[]) {
  const n = results.length;
  const avg = (vals: number[]) => vals.reduce((s, v) => s + v, 0) / n;
  const grossRs = results.map((r) => r.grossR);
  const netRs = results.map((r) => r.netR);
  const profitFactor = (rs: number[]) => {
    const wins = rs.filter((r) => r > 0).reduce((s, r) => s + r, 0);
    const losses = Math.abs(rs.filter((r) => r < 0).reduce((s, r) => s + r, 0));
    return losses > 0 ? wins / losses : Infinity;
  };

  return {
    avgGrossR: avg(grossRs),
    avgFeesR: avg(results.map((r) => r.feesR)),
    avgSlippageR: avg(results.map((r) => r.slippageR)),
    avgNetR: avg(netRs),
    grossExpectancy: avg(grossRs),
    netExpectancy: avg(netRs),
    profitFactorGross: profitFactor(grossRs),
    profitFactorNet: profitFactor(netRs),
  };
}

async function main() {
  const { signals, completedLowerTf } = await loadHistoricalSignals();
  const sysConfig = await getSystemConfiguration();
  const settings = await getSettings();

  const riskAmount = (Number(settings.riskPctPerTrade) / 100) * ASSUMED_ACCOUNT_SIZE;
  const currentRates: CostRates = {
    feeRateEntry: Number(sysConfig.feeRateEntryBps) / 10000,
    feeRateExit: Number(sysConfig.feeRateExitBps) / 10000,
    slippageRate: Number(sysConfig.slippageBps) / 10000,
  };

  console.log(`Assumed accountSize=${ASSUMED_ACCOUNT_SIZE}, riskPctPerTrade=${settings.riskPctPerTrade}% -> riskAmount=${riskAmount} per trade.`);
  console.log(`Configured rates: feeRateEntry=${sysConfig.feeRateEntryBps}bps, feeRateExit=${sysConfig.feeRateExitBps}bps, slippage=${sysConfig.slippageBps}bps (slippage is an ASSUMED figure, not empirically measured).\n`);

  function runWithRates(rates: CostRates): TradeResult[] {
    const results: TradeResult[] = [];
    for (const { index, signal } of signals) {
      const candlesAfter = completedLowerTf.slice(index + 1);
      const result = simulateTrade(signal, candlesAfter, riskAmount, rates);
      if (result) results.push(result);
    }
    return results;
  }

  const currentResults = runWithRates(currentRates);
  const agg = aggregate(currentResults);

  console.log(`${currentResults.length}/${signals.length} signals resolved within available data.\n`);
  console.log("── Cost-adjusted results (current configured rates) ──");
  console.log(`  Average gross R:    ${agg.avgGrossR.toFixed(4)}R`);
  console.log(`  Average fees R:     ${agg.avgFeesR.toFixed(4)}R`);
  console.log(`  Average slippage R: ${agg.avgSlippageR.toFixed(4)}R`);
  console.log(`  Average net R:      ${agg.avgNetR.toFixed(4)}R`);
  console.log(`  Gross expectancy:   ${agg.grossExpectancy.toFixed(4)}R per trade`);
  console.log(`  Net expectancy:     ${agg.netExpectancy.toFixed(4)}R per trade`);
  console.log(`  Profit factor gross: ${agg.profitFactorGross === Infinity ? "∞" : agg.profitFactorGross.toFixed(2)}`);
  console.log(`  Profit factor net:   ${agg.profitFactorNet === Infinity ? "∞" : agg.profitFactorNet.toFixed(2)}`);

  console.log("\n── Sensitivity: net expectancy vs fee rate (slippage held constant at configured rate) ──");
  const scenarios: Array<[string, number]> = [
    ["current fees", 1],
    ["50% lower fees", 0.5],
    ["zero fees", 0],
  ];
  for (const [label, multiplier] of scenarios) {
    const rates: CostRates = {
      feeRateEntry: currentRates.feeRateEntry * multiplier,
      feeRateExit: currentRates.feeRateExit * multiplier,
      slippageRate: currentRates.slippageRate, // held constant
    };
    const results = runWithRates(rates);
    const a = aggregate(results);
    console.log(`  ${label.padEnd(16)} netExpectancy=${a.netExpectancy.toFixed(4)}R  profitFactorNet=${a.profitFactorNet === Infinity ? "∞" : a.profitFactorNet.toFixed(2)}`);
  }
}

main();
