import { validateStrategy, type BoolExpr, type StrategyDSL } from "@sol-edge/core";

export interface Depth1Feature {
  readonly name: string; // must be a FEATURE_REGISTRY key — validateStrategy enforces this per-candidate
  readonly thresholds: readonly number[];
}

/// Inclusive linear grid of `count` values from `min` to `max`.
export function linearGrid(min: number, max: number, count: number): readonly number[] {
  if (!(count >= 2)) throw new Error(`linearGrid: count must be >= 2, got ${count}`);
  const step = (max - min) / (count - 1);
  return Array.from({ length: count }, (_, i) => min + i * step);
}

/// Exhaustive enumeration of every depth-1 (feature gt/lt const) x side
/// candidate over the given features/thresholds — no sampling, no seed.
/// Exit is NOT searched: it's mechanically derived from each candidate's
/// own entry by negating the comparison (gt<->lt) on the same feature and
/// threshold, e.g. entry "rsi_14 < 30" -> exit "rsi_14 > 30". This adds
/// zero extra degrees of freedom (Phase 10C pre-registration: exit
/// searched = N, fixed rule = mechanical negation).
export function generateDepth1Strategies(features: readonly Depth1Feature[], sides: readonly ("LONG" | "SHORT")[]): readonly StrategyDSL[] {
  const candidates: StrategyDSL[] = [];

  for (const feature of features) {
    for (const threshold of feature.thresholds) {
      for (const op of ["gt", "lt"] as const) {
        const negatedOp = op === "gt" ? "lt" : "gt";
        const entry: BoolExpr = { type: op, left: { type: "feature", name: feature.name }, right: { type: "const", value: threshold } };
        const exit: BoolExpr = { type: negatedOp, left: { type: "feature", name: feature.name }, right: { type: "const", value: threshold } };

        for (const side of sides) {
          const strategy: StrategyDSL = { side, entry, exit };
          validateStrategy(strategy);
          candidates.push(strategy);
        }
      }
    }
  }

  return candidates;
}

/// Human-readable rendering of any strategy generated by this module
/// (depth-1 or depth-2) — for reporting only, not re-parsed by anything.
/// Recursive so it handles and/or combinators, not just depth-1 gt/lt leaves.
export function describeStrategy(strategy: StrategyDSL): string {
  function describeBoolExpr(expr: BoolExpr): string {
    if (expr.type === "and") return `(${describeBoolExpr(expr.left)} AND ${describeBoolExpr(expr.right)})`;
    if (expr.type === "or") return `(${describeBoolExpr(expr.left)} OR ${describeBoolExpr(expr.right)})`;
    const left = expr.left.type === "feature" ? expr.left.name : expr.left.type === "const" ? expr.left.value : expr.left.field;
    const right = expr.right.type === "feature" ? expr.right.name : expr.right.type === "const" ? expr.right.value : expr.right.field;
    return `${left} ${expr.type === "gt" ? ">" : "<"} ${right}`;
  }
  return `${strategy.side}: enter when ${describeBoolExpr(strategy.entry)}, exit when ${describeBoolExpr(strategy.exit)}`;
}

/// Exhaustive enumeration of depth-2 conjunctions, CROSS-FEATURE pairs
/// only: one leaf from `featureA`'s grid AND one leaf from `featureB`'s
/// grid (same-feature pairs, e.g. two rsi_14 thresholds forming a band,
/// are explicitly NOT generated here — that's a different hypothesis,
/// out of scope for this generator). Exit is the De Morgan negation of
/// the entry — NOT(A) OR NOT(B) — expressed directly via the existing
/// "or" BoolExpr node, zero new searched parameters, same philosophy as
/// generateDepth1Strategies' mechanical negation.
export function generateDepth2CrossFeatureStrategies(
  featureA: Depth1Feature,
  featureB: Depth1Feature,
  sides: readonly ("LONG" | "SHORT")[],
): readonly StrategyDSL[] {
  function leavesOf(feature: Depth1Feature): readonly BoolExpr[] {
    const leaves: BoolExpr[] = [];
    for (const threshold of feature.thresholds) {
      for (const op of ["gt", "lt"] as const) {
        leaves.push({ type: op, left: { type: "feature", name: feature.name }, right: { type: "const", value: threshold } });
      }
    }
    return leaves;
  }

  function negate(leaf: BoolExpr): BoolExpr {
    if (leaf.type !== "gt" && leaf.type !== "lt") throw new Error("generateDepth2CrossFeatureStrategies: negate expects a depth-1 gt/lt leaf");
    return { type: leaf.type === "gt" ? "lt" : "gt", left: leaf.left, right: leaf.right };
  }

  const candidates: StrategyDSL[] = [];
  for (const a of leavesOf(featureA)) {
    for (const b of leavesOf(featureB)) {
      const entry: BoolExpr = { type: "and", left: a, right: b };
      const exit: BoolExpr = { type: "or", left: negate(a), right: negate(b) };
      for (const side of sides) {
        const strategy: StrategyDSL = { side, entry, exit };
        validateStrategy(strategy);
        candidates.push(strategy);
      }
    }
  }
  return candidates;
}
