import type { CompactCandle, StrategyDSL } from "@sol-edge/core";
import { FeatureEngine } from "@sol-edge/database";
import { runAstKernel } from "@sol-edge/kernel";
import { applyFriction, type SimConfig, type FrictionParams } from "@sol-edge/sim";
import { generateStrategies, type SearchSpace } from "./generator";
import { runStrategyExecution, type BacktestExecutionResult } from "./run";
import type { TemporalSplit } from "./split";
import frictionCalibration from "../../../config/frictionCalibration.json";

export interface RankedStrategy {
  readonly strategy: StrategyDSL;
  readonly trainStats: BacktestExecutionResult; // diagnostic only
  readonly testStats: BacktestExecutionResult; // SELECTION KEY
  readonly trials: number; // how many candidates were searched
  // Added in Step 9.4: raw per-trade net log returns on the TEST segment,
  // needed by significance.ts (Sharpe/skew/kurtosis require the underlying
  // distribution, not just the aggregate stats in testStats). Computed via
  // the same runAstKernel+applyFriction logic run.ts uses internally — kept
  // separate here rather than modifying run.ts's already-committed
  // BacktestExecutionResult (Step 6.1), which has no raw-array field.
  readonly testReturns: readonly number[];
}

// Defaults not specified by the given 3-arg signature (runSearch needs
// per-candle features and friction/risk assumptions to run the real
// validate->kernel->sim pipeline, neither of which space/seed/split alone
// provide). Phase 10B: these are no longer arbitrary placeholders — they
// come from config/frictionCalibration.json, generated by
// apps/worker/scripts/calibrate-friction.ts from the locked venue's real
// fee schedule, live spread snapshot, and ingested OHLCV series (see that
// file's _methodologyNote for exactly which fields are measured vs.
// assumed).
const DEFAULT_COUNT = 200;
export const DEFAULT_SIM_CONFIG: SimConfig = frictionCalibration.simConfig;
export const DEFAULT_FRICTION_PARAMS: FrictionParams = frictionCalibration.frictionParams;

/// Precomputes a features array for a candle segment, using the FULL
/// (train+test+holdout) series for causal lookback — a candle at the start
/// of test legitimately sees train's tail history (still strictly causal,
/// since train always precedes test in time); only this segment's own
/// candles are ever passed to the kernel for trading. Exported (Step 9.8)
/// so holdout.ts reuses this rather than duplicating it.
///
/// Availability convention (Step 10A.4): features for bar `c` are computed
/// as of c's CLOSE — targetTime = c.timestamp + barDurationSeconds — so
/// bar c is included (its data is known at its close) but no later bar is.
/// barDurationSeconds is inferred from the series' own spacing; the series
/// is regularly spaced by construction (gaps are handled separately by the
/// gap policy, 10A.3). For the synthetic Phase-9 pipeline (unit spacing)
/// this is exactly behavior-preserving: the +barDuration on both the
/// targetTime and the availability test cancel, so bar c is still included
/// just as before.
export function computeFeatures(segment: readonly CompactCandle[], fullSeries: readonly CompactCandle[], featureKeys: readonly string[]): Record<string, number>[] {
  const barDurationSeconds = fullSeries.length >= 2 ? fullSeries[1].timestamp - fullSeries[0].timestamp : 1;
  return segment.map((c) => {
    const record: Record<string, number> = {};
    const closeTime = c.timestamp + barDurationSeconds; // availability of bar c = the moment its signal is decided
    for (const key of featureKeys) record[key] = FeatureEngine.getFeatureSlice(key, closeTime, fullSeries, barDurationSeconds);
    return record;
  });
}

/// Single-candidate evaluation: run validate->kernel->sim on train, then
/// independently on test. Exported (beyond what the given signature
/// strictly required) because it's the directly-testable unit for "does
/// ranking actually use test stats" — runSearch is just this, looped and sorted.
export function evaluateCandidate(
  strategy: StrategyDSL,
  trainCandles: readonly CompactCandle[],
  trainFeatures: readonly Readonly<Record<string, number>>[],
  testCandles: readonly CompactCandle[],
  testFeatures: readonly Readonly<Record<string, number>>[],
  simConfig: SimConfig,
  frictionParams: FrictionParams,
): { trainStats: BacktestExecutionResult; testStats: BacktestExecutionResult; testReturns: readonly number[] } {
  const trainStats = runStrategyExecution(strategy, trainCandles, trainFeatures, simConfig, frictionParams);
  const testStats = runStrategyExecution(strategy, testCandles, testFeatures, simConfig, frictionParams);

  // Same logic runStrategyExecution uses internally (validate already ran
  // inside it above), just exposing the per-trade array for significance.ts.
  const testTrades = runAstKernel(strategy, testCandles, testFeatures);
  const testReturns = testTrades.map((trade) => applyFriction(trade, simConfig, frictionParams).netReturnLog);

  return { trainStats, testStats, testReturns };
}

export function runSearch(
  space: SearchSpace,
  seed: number,
  split: TemporalSplit,
  count: number = DEFAULT_COUNT,
  simConfig: SimConfig = DEFAULT_SIM_CONFIG,
  frictionParams: FrictionParams = DEFAULT_FRICTION_PARAMS,
): readonly RankedStrategy[] {
  const candidates = generateStrategies(space, seed, count);

  // Features computed ONCE, shared across all candidates (they don't
  // depend on the strategy, only on candles + featureKeys) — not
  // recomputed per candidate.
  const fullSeries = [...split.train, ...split.test, ...split.holdout]; // holdout is NEVER passed to the kernel below, only used for causal feature lookback continuity
  const trainFeatures = computeFeatures(split.train, fullSeries, space.featureKeys);
  const testFeatures = computeFeatures(split.test, fullSeries, space.featureKeys);

  const ranked: RankedStrategy[] = candidates.map((strategy) => {
    const { trainStats, testStats, testReturns } = evaluateCandidate(strategy, split.train, trainFeatures, split.test, testFeatures, simConfig, frictionParams);
    return { strategy, trainStats, testStats, trials: candidates.length, testReturns };
  });

  // Rank by the OUT-OF-SAMPLE (test) objective only. In-sample (train)
  // stats are carried for diagnostics and are never part of the sort key.
  ranked.sort((a, b) => b.testStats.simulatedExpectancy - a.testStats.simulatedExpectancy);

  return ranked;
}
